[package]
name = "k0105/tdtdtd"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Input = "sleitnick/input@2.3.0"
TopbarPlus = "1foreverhd/topbarplus@3.2.0"
Janitor = "1foreverhd/janitor@1.18.12"
Loader = "sleitnick/loader@2.0.0"
Promise = "evaera/promise@4.0.0"
Component = "sleitnick/component@2.4.8"
Trove = "sleitnick/trove@1.5.0"
Maid = "soda100827/maid@0.4.0"
Timer = "sleitnick/timer@1.1.2"
Shake = "sleitnick/shake@1.1.0"
spr = "blackjackiee/spr@1.1.3"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
bytenet-max = "elitriare/bytenet-max@0.2.4"
FastSignal = "lucasmzreal/fastsignal@10.4.0"
Fusion = "elttob/fusion@0.3.0"


[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
Cmdr = "evaera/cmdr@1.12.0"
